#!/bin/sh
killall udiskie
killall connman-gtk
killall flameshot
killall fcitx
killall pasystray
killall blueman-applet

udiskie &
connman-gtk &
flameshot &
fcitx &
pulseaudio -D
pasystray &
blueman-applet &

setxkbmap -option caps:ctrl_modifier

