#!/bin/sh
killall udiskie
killall connman-gtk
killall flameshot
killall fcitx
killall pasystray

udiskie &
connman-gtk &
flameshot &
fcitx &
pulseaudio -D
pasystray &

setxkbmap -option caps:ctrl_modifier

