#!/bin/sh
killall udiskie
killall connman-gtk
killall flameshot
killall fcitx
killall pulseaudio

udiskie --tray &
connman-gtk &
flameshot &
fcitx &
pulseaudio -D
pasystray &

setxkbmap -option caps:ctrl_modifier

